### ISSUE TITLE
create more than one db

### ISSUE THREAD

**Issue by orhan-swe** [lvthillo/docker-php-postgres#2]
What is the easiest way so set this up so that one can have more then one db? I guess I would need to use the postgres user somehow?

**Comment by lvthillo** [comment]
Well you can integrate [this ](https://github.com/mrts/docker-postgresql-multiple-databases) which seems a useful solution. 

You'll need to update the `docker-compose.yml` and replace
```
  postgres:
     image: postgres:9.6
```

with 
```
  postgres:
    build: ./my-directory
```

Put the script in that directory and write a dockerfile
```
$ ls my-directory/
Dockerfile
create-multiple-postgresql-databases.sh
```

In this directory you write the Dockerfile as described in the project above and put the script also there:
```
FROM postgres:9.6
COPY create-multiple-postgresql-databases.sh /docker-entrypoint-initdb.d/
```

This image will be build from the docker-compose. 
Now you can add an environment variable to the docker-compose to add multiple databases:
```
    environment:
        - POSTGRES_MULTIPLE_DATABASES=db1,db2
```

Let me know if it's clear for you.

**Comment by orhan-swe** [comment]
@lvthillo 
Thanks, your description is great, I guess I can put this in the env file also:
`POSTGRES_MULTIPLE_DATABASES=db1,db2`
Though when i do 
`docker-compose build `
the image is rebuild but I still only see the old db. Do I need to delete the old container or something?

**Comment by lvthillo** [comment]
@orhan-swe 
I'm sorry. My explanation wasn't fully correct I think. This works:

  ```
postgres:
    image: postgres:9.6
    container_name: postgres
    env_file:
      - ./env
    volumes:
      - ./script/:/docker-entrypoint-initdb.d
```

and `script/ `contains the `create-multiple-postgresql-databases.sh` script.

The content of `env` was:
```
POSTGRES_MULTIPLE_DATABASES="test-db-1","test-db-2"
POSTGRES_USER=dev
POSTGRES_PASSWORD=secret
```
I've tested this and it worked. But of course the integration with the docker-compose inside my repository will not work because my PHP application expects a variable `POSTGRES_DB` which is not set because we use `POSTGRES_MULTIPLE_DATABASES` now.

**Comment by orhan-swe** [comment]
@lvthillo 
Thanks, it worked!
