### ISSUE TITLE
psql-data file question and configuration

### ISSUE THREAD

**Issue by orhan-swe** [lvthillo/docker-php-postgres#3]
I am wondering how this is supposed to work:
psql-data:/var/lib/posgresql/data

I am not able to find psql-data

Actually my question is if it is possible to store the configuration (if i for example manually add db connections) so it is persisted between the rebuilding of the image.

**Comment by lvthillo** [comment]
The solution in this repository contains a docker-compose.yml which will create a named docker volume:
```
volumes:
psql-data:
```

This the same as:
`docker volume create psql-data`

You can list docker volumes using:
`docker volume ls`

Docker volumes are one of the 2 possible ways to persist data in your container. You can persist data on your host or in a docker volume.

This will mount the content from `/var/lib/postgresql/data` (from inside your container) to psql-data named volume:
`psql-data:/var/lib/postgresql/data`

If you delete your container and start it again with the same volume and it will mount the existing stuff in it.
You can also persist data on your host like:
`/path/on/my-host:/var/lib/postgresql/data`

With the examples above you're able to persist data of your container.
