### ISSUE TITLE
Unmet dependencies

### ISSUE THREAD

**Issue by Cage-e** [lvthillo/docker-php-postgres#4]
Compose up result: 
The following packages have unmet dependencies:
 postgresql-client-9.6 : Depends: libpq5 (>= 9.6.11) but 9.6.10-0+deb9u1 is to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'php-app' failed to build: The command '/bin/sh -c apt-get install -y postgresql-client-9.6' returned a non-zero code: 100

**Comment by lvthillo** [comment]
@Cage-e Thank you for letting me know. I've fixed the dependency. Although I need to upgrade some main versions (Already upgraded PHP but will upgrade the pgadmin etc soon). 

Pull the changes and try to rebuild with ```docker-compose up -d --build```
